### ISSUE TITLE
Connecting to Tibco JMS with SSL

### ISSUE THREAD

**Issue by arjunDhanAi** [macronova/kafka-connect-jms#5]
Hi,

We are using this library to connect to the Tibco JMS server. In Dev/Test environment things are working fine. 
When we moved to prod, we got to know that the JMS server, has an SSL certificate. When we connect the Kafka-connect with the Prod JMS server, the connection was not getting made.
We have looked at the code of the Kafka-connect, got to know there was no provision to connect to JMS with SSL.

We have added a few lines of code
https://github.com/macronova/kafka-connect-jms/blob/7646f8ddfece07e3fd96ae00edc29126f07f788e/src/main/java/io/macronova/kafka/connect/jms/common/JmsSessionProvider.java#L35
Where the "connection" object is getting instantiated. 
we added the lines  similar to the below ones
'''
TibjmsConnectionFactory factory = new com.tibco.tibjms.TibjmsConnectionFactory(serverUrl);
factory.setSSLExpectedHostName(ssl_expected_hostname);
factory.setSSLIdentity(ssl_identity,ssl_key,ssl_password);
factory.setSSLEnableVerifyHostName(false);
factory.setSSLTrustedCertificate(cert);
Connection connection = factory.createConnection(userName,password);
'''

The problem is, when we are trying to connect to the JMS server, we are still facing issues.
We get an error saying
[2021-11-30 05:14:56,426] ERROR [jms-source-text-queue|task-1] WorkerSourceTask{id=jms-source-text-queue-1} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:193)
org.apache.kafka.connect.errors.ConnectException: Failed to start JMS source task: 1 Failed to establish JMS connectivity: 2 Failed to establish JMS connectivity: Failed to connect to any server at: ssl://buwnwfblapp01.nw1.nwestnetwork.com:7243,ssl://buwnwfblapp01.nw1.nwestnetwork.com:7243...
at io.macronova.kafka.connect.jms.source.JmsSourceTask.start(JmsSourceTask.java:92)
at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:232)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:241)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.ConnectException: 1 Failed to establish JMS connectivity: 2 Failed to establish JMS connectivity: Failed to connect to any server at: ssl://buwnwfblapp01.nw1.nwestnetwork.com:7243,ssl://buwnwfblapp01.nw1.nwestnetwork.com:7243..
at io.macronova.kafka.connect.jms.common.JmsSessionProvider.<init>(JmsSessionProvider.java:66)
at io.macronova.kafka.connect.jms.common.JmsConnectionPool.getOrCreateConnection(JmsConnectionPool.java:48)
at io.macronova.kafka.connect.jms.source.JmsSourceTask.start(JmsSourceTask.java:85)
... 8 more
Caused by: org.apache.kafka.connect.errors.ConnectException: 2 Failed to establish JMS connectivity: Failed to connect to any server at: ssl://buwnwfblapp01.nw1.nwestnetwork.com:7243,ssl://buwnwfblapp01.nw1.nwestnetwork.com:7243.
at io.macronova.kafka.connect.jms.common.JmsSessionProvider.connect(JmsSessionProvider.java:140)
at io.macronova.kafka.connect.jms.common.JmsSessionProvider.<init>(JmsSessionProvider.java:62)
... 10 more
Caused by: javax.jms.JMSException: Failed to connect to any server at: ssl://buwnwfblapp01.nw1.nwestnetwork.com:7243,ssl://buwnwfblapp01.nw1.nwestnetwork.com:7243
at com.tibco.tibjms.TibjmsConnection._create(TibjmsConnection.java:1552)
at com.tibco.tibjms.TibjmsConnection.<init>(TibjmsConnection.java:4438)
at com.tibco.tibjms.TibjmsQueueConnection.<init>(TibjmsQueueConnection.java:39)
at com.tibco.tibjms.TibjmsxCFImpl._createImpl(TibjmsxCFImpl.java:202)
at com.tibco.tibjms.TibjmsxCFImpl._createConnection(TibjmsxCFImpl.java:255)
at com.tibco.tibjms.TibjmsConnectionFactory.createConnection(TibjmsConnectionFactory.java:63)
at io.macronova.kafka.connect.jms.common.JmsSessionProvider.connect(JmsSessionProvider.java:115)
... 11 more

Can you @macronova  please let us know how to solve this issue?

Thanks

**Comment by macronova** [comment]
Hi @arjunDhanAi,

Does your EMS server in Production require client SSL certificate? If not, you do not need to specify client identity. Try not to modify any code, as you can configure SSL via JNDI properties as described here (at a bottom, e.g. `com.tibco.tibjms.naming.ssl_trusted_certs`): https://docs.genesys.com/Documentation/IXN/latest/ICP/TIBCO-SSLforJMSCP. Use https://github.com/macronova/kafka-connect-jms/blob/7646f8ddfece07e3fd96ae00edc29126f07f788e/src/main/java/io/macronova/kafka/connect/jms/common/BaseConnectorConfig.java#L56 to specify the corresponding values.

Kind regards,
Macronova

**Comment by arjunDhanAi** [comment]
cool Thanks for the info. we will try to use this, and no EMS server does not need the clientIdentity, only the prod server trusted certificate is to be passed by the client.
Thanks for the quick reply.
